spring.application.name=employee-service-ribbon-lb

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/microservices

spring.datasource.username=root

spring.datasource.password=root

server.port=8080

server.servlet.context-path=/employee-app/api

address_service.base_url=http://localhost:8081/address-app/api

address-service.ribbon.listOfServers=http://localhost:8081,http://localhost:8082